feature: add change log to release CD

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -37,7 +37,17 @@ jobs:
         cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
         zip -r ${{ env.PLUGIN_NAME }}-${{ steps.build.outputs.tag_name }}.zip ${{ env.PLUGIN_NAME }}
         ls
-        echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"            
+        echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"
+
+    - name: Get release notes
+      id: release_notes
+      run: |
+        CHANGELOG=$(sed -n -e "/## ${{ steps.bundle.outputs.tag_name }}/,\## /p" CHANGELOG.md | sed '/## /d')  
+        if [ -z "$CHANGELOG" ]; then  
+          echo "Error: No release notes found for this version in CHANGELOG.md"  
+          exit 1  
+        fi  
+        echo "::set-output name=body::${CHANGELOG}"  
 
     - name: Release
       uses: softprops/action-gh-release@v1
@@ -45,7 +55,9 @@ jobs:
       with:
         token: ${{ github.token }}
         files: |
-          ${{ env.PLUGIN_NAME }}-${{ steps.build.outputs.tag_name }}.zip
+          ${{ env.PLUGIN_NAME }}-${{ steps.bundle.outputs.tag_name }}.zip
           main.js
           manifest.json
           styles.css
+        body: ${{ steps.release_notes.outputs.body }}
+
